name: Notadd Neditor 编辑器
identification: notadd/ext-neditor
description:
author:
    - Notadd
    - notadd@ibenchu.com
provider: Notadd\Neditor\Extension
publishes:
    assets/extensions/notadd/neditor/editor: resources/mixes/editor